+Filter by dog breed name
simonrowlands/NCU-Project pull request #3
Opened 2018-10-17 16:04 UTC by simonrowlands

2018-10-17 16:08 UTC, simonrowlands commented on NCU-Project/Dogs/DogsViewController.swift
> +
Is this syntax ok? Or do you prefer a more spaced out:

filteredDogs
    .subscribe {
    }
    .disposed

2018-10-18 08:21 UTC, tailec requested changes

2018-10-18 08:21 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +        let input = DogsViewModel.Input(filterString: searchBar.text ?? "")
I'd use observable instead of passing just a text

`let input = DogsViewModel.Input(filterString: searchBar.rx.text.orEmpty.asObservable())`

also renaming `filterString` to `filterText` or `query` looks better imo

2018-10-18 08:21 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +        let filteredDogs = Observable.combineLatest(searchBar.rx.text, output.networkRequestResult) { (filterString, dogs) -> [Dog] in
i think all of this should go to the view model

2018-10-18 08:21 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +
its ok 👍

2018-10-18 08:21 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +            strongSelf.tableView.reloadData()
is `strongSelf.tableView.reloadData()` needed when we use `bind(to: tableView.rx.items`? 🤔

2018-10-18 09:40 UTC, tailec requested changes

2018-10-18 09:40 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +        let input = DogsViewModel.Input(query: searchBarText)
awesome

2018-10-18 09:40 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +                self.searchBar.resignFirstResponder()
nice one, good choice of keeping this in view controller
can add `guard let strongSelf = self else { return }` because of possible memory leak here

2018-10-18 09:40 UTC, tailec commented on NCU-Project/Dogs/DogsViewModel.swift
> +        }
^ i think this should go to viewmodels `transform` function

2018-10-18 11:22 UTC, tailec requested changes

2018-10-18 11:22 UTC, tailec commented on NCU-Project/Dogs/DogsViewModel.swift
> +        let query: Observable<String?>
if we do `searchBar.rx.text.orEmpty` instead of `searchBar.rx.text` then we can make it non optional `let query: Observable<String>`

2018-10-18 11:22 UTC, tailec commented on NCU-Project/Dogs/DogsViewModel.swift
> +        return Output(networkRequestResult: filteredDogs)
can you remove whitespaces everywhere here? :)

2018-10-18 11:22 UTC, tailec commented on NCU-Project/Dogs/DogsViewController.swift
> +    private let viewModel = DogsViewModel()
nice one

2018-10-18 11:26 UTC, tailec commented on NCU-Project/Dogs/DogsViewModel.swift
>          let networkRequestResult = NetworkingAPI.getDogs()
`        let networkRequestResult = NetworkingAPI.getDogs()` not used anymore

2018-10-18 12:08 UTC, tailec approved these changes

2018-10-18 12:08 UTC, tailec commented on NCU-Project/Dogs/DogsViewModel.swift
> +                    $0.breed < $1.breed
👍

2018-10-18 12:09 UTC, merged